### ISSUE TITLE
Can't get anything visualised

### ISSUE THREAD

**Issue by mysiar** [thomasbeaujean/DoctrineRelationVisualizerBundle#1]
Instalation as per instruction to symfony 3.1.6 project.
After reaching http://localhost:8000/_visualizer
gets loaded http://localhost:8000/_visualizer/manager/default
with default screen :
<img width="304" alt="screen shot 2016-11-10 at 15 50 03" src="https://cloud.githubusercontent.com/assets/13708162/20181132/42a0f332-a75d-11e6-896c-30a57f6395c7.png">

**Comment by thomasbeaujean** [comment]
Hello,

The documentation is lacking the fact that you also have to enable another bundle in the AppKernel:

     $bundles[] = new \tbn\GetSetForeignNormalizerBundle\GetSetForeignNormalizerBundle();

The bundle is already in your vendors with composer dependencies.

The master branch was ahead the last stable tag and resolved some issues, I just created a new tag, please update the bundle:

    composer update tbn/doctrinerelationvisualizer-bundle

And then the list of entities should appears. You have to sort them by yourself.

**Comment by mysiar** [comment]
I works now great.
Thanks
<img width="770" alt="screen shot 2016-11-10 at 18 52 28" src="https://cloud.githubusercontent.com/assets/13708162/20187938/ba8bf892-a776-11e6-83f2-06058ac079f5.png">
