### ISSUE TITLE
Screenshot of the bundle output?

### ISSUE THREAD

**Issue by romainlaisne** [thomasbeaujean/DoctrineRelationVisualizerBundle#2]
Hi,

Could you provide a screenshot of what the output of the bundle looks like?

Thanks

**Comment by thomasbeaujean** [comment]
Hi, it provides something like this:
![image](https://cloud.githubusercontent.com/assets/5817919/22163354/c1c43214-df52-11e6-9c5f-3c2f77c5109d.png)

but the entities are not sorted at start, you have to sort on your own.
