### ISSUE TITLE
Create a tag v1.0.7 from master

### ISSUE THREAD

**Issue by arnaudgoulpeau** [thomasbeaujean/DoctrineRelationVisualizerBundle#6]
The master branch contains fixes for Sf4.x

It should be great to have a new tag v1.0.7 to let projects with "minimum-stability : stable" having the latest fixes.

I can help with management of this bundle if you need it.
Thanks @thomasbeaujean, see you soon !

**Comment by thomasbeaujean** [comment]
Hi, tag done.
