### ISSUE TITLE
Remarks

### ISSUE THREAD

**Issue by floviolleau** [thomasbeaujean/DoctrineRelationVisualizerBundle#7]
Hi,

Thanks for providing this bundle to the world!

Several remarks:
- can you please add the screenshot in issues to the README?
- can you please make it compatible with sf 5.4 and above? because I have several errors with TreeBuilder definition and you are using the Sensio\Bundle\FrameworkExtraBundle\ which is deprecated long time ago.

I tried some modifications but I'm stuck to:
![image](https://github.com/thomasbeaujean/DoctrineRelationVisualizerBundle/assets/5442973/260b3a82-23e2-4451-ad96-66ac2edf4565)

Thanks

**Comment by thomasbeaujean** [comment]
Hi, I will update this bundle and remove the deprecated deps. I will keep you updated.

**Comment by thomasbeaujean** [comment]
Hi, I checked and the `Symfony\Component\Config\Definition\Builder\TreeBuilder` is used,  see https://github.com/thomasbeaujean/DoctrineRelationVisualizerBundle/blob/3068020c6948c47ee2070400e1ee239cba9b83f8/DependencyInjection/Configuration.php#L5.

I do not see where FrameworkExtraBundle is used in this bundle, could you provide me more info please ?

**Comment by thomasbeaujean** [comment]
Please use the latest tag (1.1.1), I added tests and allowed sf 5.4+, it should work in your project.

If you still have your error after upgrading, let me know.
